const List<String> imuTypes = [
  'Pigeon',
  'Pigeon2',
  'CanAndGyro',
  'NavX3',
  'NavX',
  'NavX via USB',
  'NavX via SPI',
  'NavX via "OnBoard" interface',
  'NavX via MXP',
  'NavX via I2C (Dangerous)',
  'AnalogGyroscope',
  'ADIS16448',
  'ADIS16470',
  'ADXRS450',
];

const List<String> motorTypes = [
  'NEO (via SparkMAX)',
  'NEO550 (via SparkMAX)',
  'Vortex (via SparkMAX)',
  'Minion (via SparkMAX)',
  'Vortex (via SparkFlex)',
  'NEO (via SparkFlex)',
  'NEO550 (via SparkFlex)',
  'Minion (via SparkFlex)',
  'NEO (via Thrifty Nova)',
  'NEO550 (via Thrifty Nova)',
  'Vortex (via Thrifty Nova)',
  'Minion (via Thrifty Nova)',
  'Falcon500',
  'Falcon500 (CTRE PRO)',
  'Kraken x60',
  'Kraken x60 (CTRE PRO)',
];

const List<String> encoderTypes = [
  'Attached (to SparkMAX)',
  'Attached (to SparkMAX Analog Pin)',
  'Attached (to SparkMAX Analog Pin with 5V Power)',
  'CANCoder',
  'TalonSRX (PWM)',
  'TalonSRX (Analog)',
  'CANandMag (attached to SparkMAX)',
  'CANandMag (CAN)',
  'MA3 (Analog)',
  'CTRE Mag (DIO)',
  'REV Hex (DIO)',
  'AndyMark Mag (DIO)',
  'dutycycle (DIO)',
  'analog',
  'Thrifty (Analog In)',
  'REV Through Bore (DIO)',
];
